- docker-compose.yml
* Bot now restarts in case of a crash
* Renamed container
* Add data directory to volumes so user data/skins/alerts will be stored
even if the bot restarts
> Quality of life features for docker

- discord/embed.js
- valorant/battlepass.js
> Add days left to embed

- README.md
- discord/bot.js
- discord/embed.js
- reformatted README.md to align with the new update
- changed the formatting of some commands
> polishing some stuff

- discord/bot.js
- discord/embed.js
just some small edits and changing the 2nd color from #0F1923 to #202225
> made a few more polishing

- languages/de.json
- languages/es-ES.json
- languages/ja.json
- languages/ro.json
- languages/vi.json
My guy Giorgio slept on the リトライ button........
> Update retry button in different languages + some Vietnamese touch ups

- README.md
- SkinPeek.js
- discord/alerts.js
- discord/authManager.js
- discord/bot.js
- discord/embed.js
- discord/emoji.js
- languages/de.json
- languages/en-GB.json
- languages/es-ES.json
- languages/fr.json
- languages/ja.json
- languages/pt-BR.json
- languages/ro.json
- languages/th.json
- languages/vi.json
- misc/config.js
- misc/logger.js
- misc/shardMessage.js
- misc/util.js
- sharding.js
- valorant/accountSwitcher.js
- valorant/auth.js
- valorant/battlepass.js
- valorant/cache.js
- valorant/shop.js
- valorant/shopQueue.js
Overall, quite a major update, with many features long overdue.
Users can now be logged into multiple accounts on the bot, and switch between accounts without having to log in each time.
When they `/login`, instead of replacing their current account, it will add another account to the account switcher.
They can then switch accounts using `/account` and see all their accounts using `/accounts`.
They can also log out and delete one of the accounts using `/forget 3` to delete their 3rd account, for example.
Currently, the bot stores the data for all users in one giant `users.json` file, which works fine for small user bases, but now that the bot is being used in thousands of servers, [it's causing a few problems](https://www.reddit.com/r/ProgrammerHumor/comments/fcayj7/how_do_you_even_create_ …
> Add account switching, update user json format, add sharding support

- SkinPeek.bat
- SkinPeek.sh
- discord/embed.js
- misc/util.js
- valorant/shop.js
> was pushing to the wrong branch lol

- README.md
Just added the Replit version of SkinPeek to the ReadMe. It basically clones my other repository "SkinPeekReplit" (cuz I sadly can't create 2 forks of SkinPeek) to Replit. I added some files and also edited files to make an easy setup on Replit. You can also host the bot 24/7 by pinging the webserver the bot creates.
> Added Replit version of SkinPeek as button to ReadMe.

- discord/embed.js
- languages/en-GB.json
- languages/vi.json
- valorant/battlepass.js
- valorant/cache.js
The code is slightly messy, so if others want to clean it up or change certain things feel free.
> Show the next battlepass tier reward

- .gitignore
- package-lock.json
- adds `node_modules` in .gitignore
- track package-lock.json in git (needed for security reasons, check online if you want to see why)
> add some config

- Dockerfile
- discord/emoji.js
- adds some security
- improve weight
> Dockerfile improvements

- Dockerfile
the current command is written for debian-based image (my bad...)
> fix `adduser` command for alpine image

- Dockerfile
after my PR, one of the changes didnt commit correctly and it currently misses a parameter
without it, the image building doesnt work
> fix: missing parameter in Dockerfile

- Dockerfile
after some tests, it seems to break a lot of things when using local files through docker compose, so lets revert it
> revert user restriction in dockerfile

- valorant/cache.js
> fixed Araxys bulldog display icon

- discord/bot.js
- discord/embed.js
- discord/emoji.js
- misc/languages.js
- misc/logger.js
- misc/settings.js
- misc/util.js
- package-lock.json
- package.json
Will merge in a few days if no one reports any bugs :)
> Update to discord.js v14

- discord/bot.js
- discord/embed.js
- languages/en-GB.json
> added the ability to inspect weapons from shop/nightmarket/collections/bundles

- discord/bot.js
due to the appearance of StringSelectMenuComponent as a new component, an attempt was made to create a button from the SelectMenu
> fixed loading of components with multiple accs

- languages/th.json
Improved translation of some sentences due to spelling errors in Thai in some sentences
> Improved translation of some sentences

- .github/dependabot.yml
This PR introduces a Dependabot configuration file to automate dependency updates. Dependabot helps keeping the dependencies up-to-date, ensuring everyone benefits from the latest features, bug fixes, and security patches.
Changes Introduced:
- Added a `.github/dependabot.yml` file to configure Dependabot
- Configured Dependabot to check for updates on a weekly basis
> Enable dependabot for automatic dependency updates

- valorant/shop.js
> Add an empty body for fix error 400
